// SPDX-FileCopyrightText: 2026 marunine
// SPDX-License-Identifier: LGPL-3.0-only
// GENERATED FILE - do not edit by hand.
// Generator: tools/gen-meiki-corrections.py
// Source: operational correction specification, sha256
// 46e49de1589539a3d028140af6418a9e9f820977b15e20c12191a0aab5c9ed16. 74 rules, in application order. See
// tools/data/README.md.
#pragma once

#include "ocr/meikicorrections.h"

#include <array>

namespace maru::ocr
{

inline constexpr std::array<CorrectionRule, 74> kMeikiCorrectionRules = {{
    CorrectionRule{.find = u"…",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x2026},
                              {.kind = CorrectionToken::Kind::Literal, .character = 0x2026}}},
                   .afterCount = 2,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"一",
                   .replace = u"「",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Vertical,
                   .maxConfidence = 0.7},
    CorrectionRule{.find = u"\uFFFD",
                   .replace = u".",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"、",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"ー",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.4},
    CorrectionRule{.find = u"一",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"っ",
                   .replace = u"。",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"、",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Other, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"し",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"っ",
                   .replace = u"。",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x305F}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.6},
    CorrectionRule{.find = u"ゃ",
                   .replace = u"。",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Vertical,
                   .maxConfidence = 0.5},
    CorrectionRule{.find = u"し",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.4},
    CorrectionRule{.find = u"っ",
                   .replace = u"。",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.4},
    CorrectionRule{.find = u"。",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"....",
                   .replace = u"……",
                   .before = {{{.kind = CorrectionToken::Kind::Hiragana, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Hiragana, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.5},
    CorrectionRule{.find = u"、",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Other, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Vertical,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"|",
                   .replace = u"「",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"I",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Latin, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Latin, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.6},
    CorrectionRule{.find = u"に",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"に",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.4},
    CorrectionRule{.find = u"x",
                   .replace = u"×",
                   .before = {{{.kind = CorrectionToken::Kind::Other, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"を",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"・",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Other, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"と",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.5},
    CorrectionRule{.find = u"バ",
                   .replace = u"パ",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x30A2}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Katakana, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.8},
    CorrectionRule{.find = u"〔",
                   .replace = u"(",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"つ",
                   .replace = u"っ",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Other, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.7},
    CorrectionRule{.find = u"ノ",
                   .replace = u"/",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.5},
    CorrectionRule{.find = u"へ",
                   .replace = u"、",
                   .before = {{{.kind = CorrectionToken::Kind::Hiragana, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.4},
    CorrectionRule{.find = u"コ",
                   .replace = u"「",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Vertical,
                   .maxConfidence = 0.4},
    CorrectionRule{.find = u"牛",
                   .replace = u"生",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.8},
    CorrectionRule{.find = u"ノ",
                   .replace = u"/",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.5},
    CorrectionRule{.find = u"二",
                   .replace = u"「",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Hiragana, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.6},
    CorrectionRule{.find = u"の",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"・",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Hiragana, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"つ",
                   .replace = u"っ",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x305F}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.7},
    CorrectionRule{.find = u"2",
                   .replace = u"?",
                   .before = {{{.kind = CorrectionToken::Kind::Hiragana, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.4},
    CorrectionRule{.find = u"く",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"ト",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.4},
    CorrectionRule{.find = u"ュ",
                   .replace = u"・",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Vertical,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"―",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"T",
                   .replace = u"「",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"ン",
                   .replace = u"】",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.6},
    CorrectionRule{.find = u"一",
                   .replace = u"ー",
                   .before = {{{.kind = CorrectionToken::Kind::Hiragana, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.7},
    CorrectionRule{.find = u"で",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"こ",
                   .replace = u"、",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"イ",
                   .replace = u"(",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"二",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"て",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"で",
                   .replace = u"・",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"、",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x308B}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"」",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"い",
                   .replace = u"、",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"大",
                   .replace = u"太",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x90CE}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u":",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Latin, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Digit, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u".",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x2026},
                               {.kind = CorrectionToken::Kind::Literal, .character = 0x2026}}},
                   .beforeCount = 2,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"ア",
                   .replace = u"ァ",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x30D5}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.9},
    CorrectionRule{.find = u"・",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Katakana, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"プ",
                   .replace = u"ブ",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x30BF}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.9},
    CorrectionRule{.find = u".",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x0050}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Digit, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"ン",
                   .replace = u"シ",
                   .before = {{{.kind = CorrectionToken::Kind::Hiragana, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Katakana, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Vertical,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"、",
                   .replace = u"",
                   .before = {{{.kind = CorrectionToken::Kind::Katakana, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.1},
    CorrectionRule{.find = u"ビ",
                   .replace = u"ピ",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x30B3}, {}}},
                   .beforeCount = 1,
                   .after = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x30FC}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"I",
                   .replace = u"「",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"べ",
                   .replace = u"、",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Vertical,
                   .maxConfidence = 0.3},
    CorrectionRule{.find = u"た",
                   .replace = u"",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::LineEdge, .character = 0}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.2},
    CorrectionRule{.find = u"つ",
                   .replace = u"っ",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x3068}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.7},
    CorrectionRule{.find = u"ボ",
                   .replace = u"ポ",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x30B1}, {}}},
                   .afterCount = 1,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.9},
    CorrectionRule{.find = u"ニ",
                   .replace = u"二",
                   .before = {{{.kind = CorrectionToken::Kind::Kanji, .character = 0}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.8},
    CorrectionRule{.find = u"て",
                   .replace = u"で",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x306A},
                               {.kind = CorrectionToken::Kind::Literal, .character = 0x3044}}},
                   .beforeCount = 2,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Horizontal,
                   .maxConfidence = 0.9},
    CorrectionRule{.find = u"某",
                   .replace = u"基",
                   .before = {{{}, {}}},
                   .beforeCount = 0,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.9},
    CorrectionRule{.find = u"ば",
                   .replace = u"ぱ",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x3063}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Vertical,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"て",
                   .replace = u"で",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x307E}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = std::nullopt},
    CorrectionRule{.find = u"た",
                   .replace = u"だ",
                   .before = {{{.kind = CorrectionToken::Kind::Literal, .character = 0x3093}, {}}},
                   .beforeCount = 1,
                   .after = {{{}, {}}},
                   .afterCount = 0,
                   .mode = CorrectionMode::Any,
                   .maxConfidence = 0.7},
}};

} // namespace maru::ocr
